version: '3.8'

services:

  db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    depends_on:
      - db
